TencentBlueKing/bk-training-open

frontend/src/views/myDaily/index.vue, home_application/urls.py, home_application/views.py
1. 添加获取当前用户所有组下的模板接口;
2. 初步完成写日报页面
=> feature: 1. 添加获取当前用户所有组下的模板接口; 2. 初步完成写日报页面

blueapps/account/components/bk_token/backends.py, config/default.py, home_application/celery_task.py, home_application/models.py, home_application/utils/get_people_for_mail_notify.py, home_application/utils/mail_operation.py, home_application/utils/report_operation.py, home_application/views.py
(1) 每天早上8点发送前一天日报
(2) 每天晚上10点提醒写日报
(3) 获取日报时，将日报内容格式化为json
=> feature: 1. 添加定时发邮件任务; 2. 修改获取到的日报内容格式为json

config/default.py, home_application/celery_task.py, home_application/templates/email_templates/daily_report.html, home_application/utils/get_people_for_mail_notify.py
=> feature: 使用html内容发送前一天日报

home_application/celery_task.py, home_application/models.py, home_application/templates/email_templates/daily_report.html, home_application/utils/get_people_for_mail_notify.py, home_application/views.py
1. 添加日报和周报两个默认模板
2. 前一天日报邮件发送后修改状态为已发送
3. 修改用户名显示为username(name)的格式
4. 修复日报邮件在QQ归类显示中不会居中的问题
=> bugfix: 1. 添加日报和周报两个默认模板; 2. 前一天日报邮件发送后修改状态为已发送; 3. 修改用户名显示为username(name)的格式; 4. 修复日报邮件在QQ归类显示中不会居中的问题

frontend/src/App.vue, frontend/src/views/Home/index.vue, frontend/src/views/groupDailys/index.vue
bugfix - 1. 导航栏高亮显示 2.日报状态切换标签，显示右移
=> bugfix - 1. 导航栏高亮显示 2.日报状态切换标签，显示右移

frontend/src/App.vue, frontend/src/views/Home/index.vue, frontend/src/views/groupDailys/index.vue, frontend/src/views/myGroup/index.vue, home_application/urls.py, home_application/views.py
bugfix - 1. 新增-删除组（删除组模板、组用户连接信息） 2.管理员用户"移除"项置灰  3.处理新增日报或者编辑日报时，沾上上一个向后台提交的表单内容的问题 4.解决路由点击跳转不灵敏的bug 4.没有组时，隐藏新增模板、新增组按键  5.没有日报时，日报数量显示在提示语句上面
=> bugfix - 1. 新增-删除组（删除组模板、组用户连接信息） 2.管理员用户"移除"项置灰  3.处理新增日报或者编辑日报时，沾上上一个向后台提交的表单内容的问题 4.解决路由点击跳转不灵敏的bug 4.没有组时，隐藏新增模板、新增组按键  5.没有日报时，日报数量显示在提示语句上面

home_application/celery_task.py, home_application/templates/email_templates/readme.md, home_application/templates/email_templates/simple_notify.html
feature: 新增简单通知邮件模板，将对应的简单通知都改为此模板
=> feature: 新增简单通知邮件模板，将对应的简单通知都改为此模板

frontend/src/views/Home/index.vue, home_application/celery_task.py, home_application/views.py
=> bugfix: 修复补写日报时没有通知管理员的疏漏

home_application/utils/get_people_for_mail_notify.py, home_application/views.py
=> bugfix: 修复给管理员发送邮件时管理员字符串拼接错误

blueapps/account/components/bk_token/backends.py
=> optimize: group user

home_application/views.py
=> bugfix: 修改数据库中admin字段的存储格式为逗号连接的用户名

home_application/celery_task.py, home_application/views.py
sprintfix- 1.管理员处理完申请入组请求后，发送邮件给用户反馈结果  2.通过邮件发送申请入组请求给管理员、发送申请入组处理结果套用通用邮件模板
=> sprintfix- 1.管理员处理完申请入组请求后，发送邮件给用户反馈结果  2.通过邮件发送申请入组请求给管理员、发送申请入组处理结果套用通用邮件模板

home_application/admin_views.py, home_application/celery_task.py, home_application/utils/mail_operation.py
sprintfix: 修改提醒未写日报用户的邮件模板&发送日报概览后更新日报状态
=> sprintfix: 修改提醒未写日报用户的邮件模板&发送日报概览后更新日报状态

home_application/admin_views.py, home_application/utils/mail_operation.py
=> feature-管理员后端

home_application/utils/mail_operation.py
=> sprintfix: 修改邮件链接中的跳转路由

home_application/celery_task.py, home_application/utils/mail_operation.py
=> minor: 修改定时任务的日志打印，添加具体的参数

home_application/admin_views.py
=> bugfix:请假功能

frontend/src/views/Home/index.vue, frontend/src/views/groupDailys/index.vue, frontend/src/views/manageGroup/index.vue, frontend/src/views/myGroup/index.vue
Reverts TencentBlueKing/bk-training-open#180
=> Revert "bugfix:请假及优秀日报bug修复"

home_application/admin_views.py, home_application/models.py
feature： 请假功能新增 返回当前人今天后所有的请假时间
bugfix: 日报分享缺少一次判断 会当中判断管理员是否评价值判断一次
：每周空闲时间后端，返回值增加 id 字段
=> bugfix + feature

frontend/src/views/groupDailys/index.vue, frontend/src/views/myGroup/index.vue
=> bugfix: 修复没有加入任何组的时候报错问题

frontend/src/views/Home/index.vue, frontend/src/views/groupDailys/index.vue, frontend/src/views/index.vue, frontend/src/views/manageGroup/index.vue, frontend/src/views/myGroup/index.vue, home_application/views.py
=> feature: 添加用户支持批量添加

frontend/src/views/Home/index.vue, frontend/src/views/groupDailys/index.vue, frontend/src/views/index.vue, frontend/src/views/manageGroup/index.vue, frontend/src/views/myGroup/index.vue
任务展示（1）=> 1.
table列数增多默认全局隐私
未填写时弹出消息
发送给他按钮一直显示
日报标题减小
dialog变高
=> sprintfix:解决了以下问题

frontend/src/views/myGroup/index.vue
bugfix: 修复快速切换时导致当前组加载状态错误的bug
=> bugfix: 修复快速切换时导致当前组加载状态错误的bug

frontend/src/App.vue, frontend/src/views/myGroup/index.vue, home_application/urls.py, home_application/utils/tools.py, home_application/views.py
1.非管理员看不到管理组页面
2.非管理员禁用添加成员按钮
3.非管理员不显示操作栏
4.管理员移除成员时先出弹框
5.选中组名后，刷新页面，会恢复为已选中的小组
=> bugfix - 修复管理员权限相关bug

home_application/admin_views.py
管理员界面 分享日报改为不分享给管理员         
请假功能 展示请假人时间由只展示今天的请假信息 改为展示今天及以后的请假信息
=> bugfix： 管理员界面+ 请假功能

frontend/src/views/Home/index.vue, home_application/celery_task.py, home_application/templates/email_templates/all_excellent.html, home_application/templates/email_templates/excellent.html, home_application/utils/mail_operation.py
=> bugfix: 修正邮件中放入本地开发链接的bug

blueapps/patch/settings_open_saas.py
=> bugfix: 修改SITE_URL对应的环境变量

config/default.py, home_application/celery_task.py, home_application/utils/mail_operation.py
bugfix: 修改网站完整url的环境变量为BKAPP_FULL_SITE_URL
=> bugfix: 修改网站完整url的环境变量为BKAPP_FULL_SITE_URL

README.md, config/default.py, home_application/templates/email_templates/group_daily.html, home_application/utils/mail_operation.py, home_application/utils/report_operation.py, home_application/views.py
=> feature: 日报推送邮件中增加日报详细信息

home_application/utils/mail_operation.py
=> bugfix: 临时修复KeyError的bug

home_application/celery_task.py, home_application/templates/email_templates/group_daily.html, home_application/utils/mail_operation.py
bugfix: 完成邮件优化，在管理员收到的邮件中添加日报信息
=> bugfix: 完成邮件优化，在管理员收到的邮件中添加日报信息

home_application/templates/email_templates/daily_email.html, home_application/utils/mail_operation.py, home_application/utils/report_operation.py
=> bugfix: 完成邮件重写，修改为按组发送邮件

home_application/admin.py, home_application/views/off_day.py
=> feature: 细化管理员直接操作节假日表的方式

home_application/admin.py
=> feature: 超级管理员页面增加系统中重要的几个表

home_application/admin.py
=> feature: 超级管理员页面节假日表按照年月日降序排序

home_application/templates/email_templates/daily_email.html, home_application/utils/mail_operation.py
feature: 管理员邮件改为每行显示两个日报
邮件中跳转查看个人日报的链接已经设计好，等子龙页面优化完再加上
=> feature: 管理员邮件改为每行显示两个日报

frontend/src/App.vue, frontend/src/views/myGroup/index.vue
=> bugfix:管理员置顶 改为sort

frontend/src/views/Home/index.vue, home_application/utils/mail_operation.py
bugfix: 修复多重日报的bug，发送邮件添加sleep
=> bugfix: 修复多重日报的bug，发送邮件添加sleep

home_application/views/daily.py
=> minor: 优化日报获取和新增的逻辑

config/default.py, home_application/urls.py, home_application/views/authority_center.py, home_application/views/iam_view.py
=> feature: 完成权限中心资源反拉接口

frontend/src/components/GroupDailys/ExcellentDaily/index.css, frontend/src/components/GroupDailys/ExcellentDaily/index.vue, frontend/src/components/GroupDailys/FastBtn/index.vue, frontend/src/components/GroupDailys/GroupDaily/index.css, frontend/src/components/GroupDailys/GroupDaily/index.vue
=> feature:日期切换 & 人员切换

frontend/src/components/GroupDailys/GroupDaily/index.vue
=> bugfix：我的小组首屏日期没有数据

frontend/build/webpack.base.conf.js, frontend/src/api/daily/index.js, frontend/src/components/GroupDailys/GroupDaily/index.vue, frontend/src/components/Home/Onoff/index.vue, frontend/src/views/Home/index.css, frontend/src/views/Home/index.vue, frontend/src/views/myGroup/index.css
feature：添加日报界面修改，js优化 。 日报查看成员下拉框显示内容改为账号加姓名防止用户重名
=> feature：添加日报界面修改，js优化 。 日报查看成员下拉框显示内容改为账号加姓名防止用户重名

frontend/src/views/Home/index.css
=> minor：颜色修改

frontend/src/App.vue, frontend/src/components/GroupDailys/ExcellentDaily/index.css, frontend/src/components/GroupDailys/ExcellentDaily/index.vue, frontend/src/components/GroupDailys/GroupDaily/index.css, frontend/src/components/GroupDailys/GroupDaily/index.vue, frontend/src/router/index.js
feature：去除管理组 & 在日报查看新增设为优秀日报和取消优秀日报
=> feature：去除管理组 & 在日报查看新增设为优秀日报和取消优秀日报

frontend/src/components/GroupDailys/ExcellentDaily/index.css, frontend/src/components/GroupDailys/GroupDaily/index.css
=> minor：日报查看 解决英文和数组过长不换行问题

README.md, config/__init__.py, config/default.py, home_application/utils/iam_util.py
=> bugfix: 增加蓝鲸SaaS平台url环境变量

README.md, config/default.py, home_application/urls.py, home_application/utils/tools.py, home_application/views/__init__.py, home_application/views/daily.py, home_application/views/group.py, home_application/views/user.py
=> minor: 对代码细节进行优化和改正

home_application/models/daily.py, home_application/views/daily.py
=> feature: 评价日报增加管理员姓名

frontend/src/views/groupDailys/index.vue, frontend/src/views/myGroup/index.vue
bugfix：解决新用户访问我的小组没有组时 弹窗报错，没有组不允许访问日报查看
=> bugfix：解决新用户访问我的小组没有组时 弹窗报错，没有组不允许访问日报查看
